//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 實驗室管理.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookbuyers
    {
        public string name { get; set; }
        public int book_ID { get; set; }
        public string book_name { get; set; }
        public string ISBN { get; set; }
        public string author { get; set; }
        public string publicsh { get; set; }
        public Nullable<int> book_borrow_ID { get; set; }
        public Nullable<int> user_ID { get; set; }
    }
}
