//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 實驗室管理.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_reserve
    {
        public int book_reserve_ID { get; set; }
        public System.DateTime reserve_time { get; set; }
        public System.DateTime book_back_time { get; set; }
        public System.DateTime book_retain_time { get; set; }
        public int user_ID { get; set; }
        public int book_ID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
