//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 實驗室管理.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Laboratoryborrow1Entities : DbContext
    {
        public Laboratoryborrow1Entities()
            : base("name=Laboratoryborrow1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Auth> Auths { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<book_borrow> book_borrow { get; set; }
        public virtual DbSet<book_overdue> book_overdue { get; set; }
        public virtual DbSet<book_reserve> book_reserve { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
